export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";

export const LOAD_INITIAL_DATA = "LOAD_INITIAL_DATA";
export const RESET_INITIAL_DATA = "RESET_INITIAL_DATA";