import "@repo/ui/styles.css";
import "./globals.css";
import type {Metadata} from "next";
import {GeistSans} from "geist/font/sans";
import {NextIntlClientProvider} from 'next-intl';
import {ReactNode} from 'react';

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export type Props = {
  children: ReactNode;
};

export default function RootLayout({children}: Props) {
  return (
      <html lang="en">
      <body className={GeistSans.className}>
      <NextIntlClientProvider locale="en">
        {children}
      </NextIntlClientProvider>
      </body>
      </html>
  );
}
