import "@repo/ui/styles.css";
import "./globals.css";
import type {Metadata, Viewport} from "next";
import {NextIntlClientProvider} from 'next-intl';
import {ReactNode} from 'react';
import {Inter} from 'next/font/google';
import {ThemeProvider} from 'next-themes';

const inter = Inter({weight: ['700', '600', '500', '400']});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export const viewport: Viewport = {
  userScalable: false,
  width: "device-width",
  initialScale: 1.0,
}

export type Props = {
  children: ReactNode;
};

export default function RootLayout({children}: Props) {
  return (
      <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <NextIntlClientProvider locale="en">
        <ThemeProvider
            defaultTheme="system"
            enableSystem={true}
            enableColorScheme={true}
        >
        {children}
        </ThemeProvider>
      </NextIntlClientProvider>
      </body>
      </html>
  );
}
