import {ProjectType} from '@/content/types';

export const portfolio: ProjectType[] = [
  {
    id: "bee-funded",
    name: "BeeFunded",
    owner: "IGDev",
    imageSrc: "/projects/bee-funded.png",
    tech: [
        'TypeScript',
        'Nest.js',
        'React',
        'Vite',
        'Rest API Integration',
        'ethers.js',
    ],
    stage: "mvp",
    status: "archived",
    summary: "Web3 donation platform built on Ethereum Blockchain built during Chainlink Hackathon.",
    repositoryUrl: "https://github.com/igdev0/bee-funded",
  },
  {
    id: "pro-scan-solutions",
    name: "Pro Scan Solutions",
    owner: "IGDev",
    stage: "production",
    status: "completed",
    summary: "Multipage website translated from figma design spec provisioned built with TypeScript, NextJS driven by a Strapi CMS.",
    imageSrc: "/projects/pro-scan-solutions.png",
    appUrl: "https://pro-scan-solutions.ro",
    tech: [
        'Next.js',
        'Styled-Components',
        'Strapi CMS',
        'GraphQL API Integration',
        'Figma',
    ],
  },
  {
    id: "igdev",
    name: "IGDev personal website",
    owner: "IGDev",
    stage: "production",
    status: "active",
    summary: "Redesigned and developed my personal website to better showcase my work experience and skills.",
    repositoryUrl: "https://github.com/igdev0/portfolio",
    tech: [
        'Next.js (App Router)',
        'TypeScript',
        'TailwindCSS',
        'FramerMotion',
        'Payload',
        'GraphQL API Integration'
    ],
  },
  {
    id: "identus",
    name: "Identus",
    owner: "IOG",
    stage: "mvp",
    status: "completed",
    imageSrc: "/projects/hyperledger-identus.png",
    summary: "Hyperledger Identus lets organizations issue, manage, and verify digital identities and credentials using decentralized identity standards.",
    appUrl: "https://hyperledger-identus.github.io",
    tech: [
        'TypeScript',
        'Styled-Components',
        'Figma',
        'Jest',
        'Cypress',
        'Rest API Integration',
        'Storybook',
        'FramerMotion'
    ],
  },
  {
    id: "collect-plus",
    name: "Collect+",
    owner: "FinerVision",
    stage: "production",
    status: "active",
    imageSrc: "/projects/collect-plus.png",
    summary: "Developed and maintained the Collect+ frontend, implementing end-to-end parcel drop-off, returns, and tracking UI integrated with multiple courier APIs and real-time status updates.",
    appUrl: "https://www.collectplus.co.uk",
    tech: ['TypeScript', 'Next.js', 'Scss', 'Rest API Integration'],
  },
  {
    id: "star-app",
    name: "STAR App",
    owner: "FinerVision",
    stage: "production",
    status: "active",
    imageSrc: "/projects/star.png",
    summary: "Developed the core frontend features for the STAR App, a medical application for patients with ATTR amyloidosis.",
    appUrl: "https://apps.apple.com/gb/app/star-the-symptom-tracker/id1560476806?platform=iphone",
    tech: [
        'React Native',
        'Expo',
        'TypeScript',
        'Sqlite',
        'Native API Integration'
    ],
  },
  {
    id: "bluespherebio",
    name: "ATB Therapeutics",
    owner: "FinerVision",
    stage: "production",
    status: "active",
    imageSrc: "/projects/atb-therapeutics-logo.svg",
    summary: "Developed the core features for ATB therapeutics website, implementing the design specification from Figma.",
    appUrl: "https://atbtherapeutics.com/",
    tech: [
        'Next.js',
        'TypeScript',
        'Strapi CMS',
        'GraphQL API Integration',
    ],
  }
];