import {ProjectType} from '@/content/types';

export const portfolio: ProjectType[] = [
  {
    id: "bee-funded",
    name: "BeeFunded",
    owner: "IGDev",
    imageSrc: "/projects/bee-funded.png",
    tech: [
        'TypeScript',
        'Nest.js',
        'React',
        'Vite',
        'Rest API Integration',
        'ethers.js',
        'hardhat',
    ],
    stage: "mvp",
    status: "archived",
    summary: "Developed a Web3 donation platform on Ethereum during the Chainlink Hackathon, implementing smart contract-based donation flows for on-chain contributions.",
    repositoryUrl: "https://github.com/igdev0/bee-funded",
  },
  {
    id: "pro-scan-solutions",
    name: "Pro Scan Solutions",
    owner: "IGDev",
    stage: "production",
    status: "completed",
    summary: "Developed a multi-page i8n website for Pro Scan Solutions, implementing a Next.js frontend based on Figma designs with Strapi CMS and GraphQL integration for dynamic content.",
    imageSrc: "/projects/pro-scan-solutions.png",
    appUrl: "https://pro-scan-solutions.ro",
    tech: [
        'Next.js',
        'Styled-Components',
        'Strapi CMS',
        'GraphQL API Integration',
        'Figma',
    ],
  },
  {
    id: "igdev",
    name: "IGDev personal website",
    owner: "IGDev",
    stage: "production",
    status: "active",
    summary: "Built and redesigned my personal website to showcase projects and experience using a modern Next.js stack with TailwindCSS, Framer Motion, and Payload CMS.",
    repositoryUrl: "https://github.com/igdev0/portfolio",
    tech: [
        'Next.js (App Router)',
        'TypeScript',
        'TailwindCSS',
        'FramerMotion',
        'Payload',
        'GraphQL API Integration'
    ],
  },
  {
    id: "identus",
    name: "Identus",
    owner: "IOG",
    stage: "mvp",
    status: "completed",
    imageSrc: "/projects/hyperledger-identus.png",
    summary: "Hyperledger Identus lets organizations issue, manage, and verify digital identities and credentials using decentralized identity standards.",
    appUrl: "https://hyperledger-identus.github.io",
    tech: [
        'TypeScript',
        'Styled-Components',
        'Figma',
        'Jest',
        'Cypress',
        'Rest API Integration',
        'Storybook',
        'FramerMotion'
    ],
  },
  {
    id: "collect-plus",
    name: "Collect+",
    owner: "FinerVision",
    stage: "production",
    status: "active",
    imageSrc: "/projects/collect-plus.png",
    summary: "Built and maintained the Collect+ frontend, delivering core parcel drop-off, returns, and tracking experiences integrated with multiple courier APIs and real-time shipment status updates.",
    appUrl: "https://www.collectplus.co.uk",
    tech: ['TypeScript', 'Next.js', 'Scss', 'Rest API Integration'],
  },
  {
    id: "star-app",
    name: "STAR App",
    owner: "FinerVision",
    stage: "production",
    status: "active",
    imageSrc: "/projects/star.png",
    summary: "Implemented core frontend functionality for STAR App, a React Native symptom tracking app for patients with ATTR amyloidosis, enabling daily health logging and data management.",
    appUrl: "https://apps.apple.com/gb/app/star-the-symptom-tracker/id1560476806?platform=iphone",
    tech: [
        'React Native',
        'Expo',
        'TypeScript',
        'Sqlite',
        'Native API Integration'
    ],
  },
  {
    id: "bluespherebio",
    name: "ATB Therapeutics",
    owner: "FinerVision",
    stage: "production",
    status: "active",
    imageSrc: "/projects/atb-therapeutics-logo.svg",
    summary: "Developed the ATB Therapeutics website, implementing a Next.js frontend from Figma designs with Strapi CMS and GraphQL API integration for dynamic content management.",
    appUrl: "https://atbtherapeutics.com/",
    tech: [
        'Next.js',
        'TypeScript',
        'Strapi CMS',
        'GraphQL API Integration',
    ],
  }
];