import type {Metadata} from "next";
import {Klee_One, Kode_Mono} from "next/font/google";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const klee = Klee_One({weight: ["600", "400"], subsets: ["latin", "cyrillic"]});
const kode = Kode_Mono({weight: ["600", "400"], subsets: ['latin', 'latin-ext']});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${klee.className} ${kode.className}`}>
        {children}
      </body>
    </html>
  );
}
