# src/queries/posts.queries

query getBlogs($limit: Int = 3) {
    Blogs(limit: $limit) {
        docs {
            category {
                title
            },
            title,
        },
        limit
    },
}