export const FETCH_SCHOOLS = "FETCH_SCHOOLS";
export const UPDATE_SCHOOL = "UPDATE_SCHOOL";
export const UPDATE_SCHOOL_SKILLS = "UPDATE_SCHOOL_SKILLS";
export const DELETE_SCHOOL = "DELETE_SCHOOL";
export const CREATE_SCHOOL ="CREATE_SCHOOL";

export const CREATE_SKILL = "CREATE_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const FETCH_SKILLS = "FETCH_SKILLS";

export const LOAD_INITIAL_DATA__FOR__SKILL = "LOAD_INITIAL_DATA__FOR__SKILL";
export const LOAD_INITIAL_DATA__FOR__SCHOOL = "LOAD_INITIAL_DATA__FOR__SCHOOL";

export const FETCH_PROFILE_INTRODUCTION = "FETCH_PROFILE_INTRODUCTION";
export const UPDATE_PROFILE_INTRODUCTION = "UPDATE_PROFILE_INTRODUCTION";